name: Create an issue

on: [pull_request, push]

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python main.py
      - uses: JasonEtco/create-an-issue@v2
        name: Create issue if failed
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/failed_schedule_issue_template.md
