name: docker

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
#       - uses: docker/setup-buildx-action@v1
#       - uses: docker/build-push-action@v2
#         with:
#           push: false
#           tags: pytorchignite/base:latest
#           file: Dockerfile
#           build-args: |
#             PTH_VERSION=1.7.0-cuda11.0-cudnn8
      - run: docker build --build-arg=1.7.1-cuda11.0-cudnn8 -t pytorchignite/base:latest -f Dockerfile .
      - run: docker images | grep pytorchignite
