name: Build docs

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ignite
    steps:
      - run: git clone https://github.com/ydcjeff/ignite.git --branch docs/katex
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('docs/requirements.txt') }}

      - name: Install docs deps
        run: bash .github/workflows/install_docs_deps.sh

      - name: Build docs
        run: bash .github/workflows/build_docs.sh
