name: Lightning

on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  conda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pytorch_channel: [pytorch-nightly, pytorch-test]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - run: conda install pytorch -c ${{ matrix.pytorch_channel }}
      - run: git clone https://github.com/PyTorchLightning/pytorch-lightning
      - run: pip install -r requirements/devel.txt -U
        working-directory: pytorch-lightning
      - run: python -m torch.utils.collect_env
      - run: pytest pytorch_lightning tests -v -ra
        working-directory: pytorch-lightning

  pip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pytorch_channel: [nightly, test]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: pip install --pre torch torchvision torchaudio torchtext -f https://download.pytorch.org/whl/${{ matrix.pytorch_channel }}/cpu/torch_${{ matrix.pytorch_channel }}.html
      - run: git clone https://github.com/PyTorchLightning/pytorch-lightning
      - run: pip install -r requirements/devel.txt -U
        working-directory: pytorch-lightning
      - run: python -m torch.utils.collect_env
      - run: pytest pytorch_lightning tests -v -ra
        working-directory: pytorch-lightning
